module.exports = {
  icDesignSidebar: [
    {
      type: 'category',
      label: '芯片设计',
      collapsible: true,
      collapsed: false,
      items: [
        'ic-design/intro',
        {
          type: 'category',
          label: '数字电路设计',
          collapsible: true,
          collapsed: false,
          items: [
            'ic-design/digital/design-rules',
            'ic-design/digital/timing-analysis',
            'ip-core/overview',
          ],
        },
      ],
    },
  ],

  processSidebar: [
    {
      type: 'category',
      label: '工艺与制造',
      collapsible: true,
      collapsed: false,
      items: [
        'process/intro',
        {
          type: 'category',
          label: '工艺技术节点',
          collapsible: true,
          collapsed: true,
          items: [
            'process/nodes/7nm-5nm',
            'process/nodes/finfet',
          ],
        },
        {
          type: 'category',
          label: '封装测试',
          collapsible: true,
          collapsed: true,
          items: [
            'process/packaging/sip',
          ],
        },
      ],
    },
  ],

  edaToolsSidebar: [
    {
      type: 'category',
      label: 'EDA工具',
      collapsible: true,
      collapsed: false,
      items: [
        'eda-tools/intro',
        {
          type: 'category',
          label: 'Cadence工具',
          collapsible: true,
          collapsed: true,
          items: [
            'eda-tools/cadence/virtuoso',
          ],
        },
        {
          type: 'category',
          label: 'Synopsys工具',
          collapsible: true,
          collapsed: true,
          items: [
            'eda-tools/synopsys/design-compiler',
            'eda-tools/synopsys/primetime',
          ],
        },
        {
          type: 'category',
          label: '开源工具',
          collapsible: true,
          collapsed: true,
          items: [
            'eda-tools/opensource/openroad',
          ],
        },
      ],
    },
  ],

  standardsSidebar: [
    {
      type: 'category',
      label: '协议与标准',
      collapsible: true,
      collapsed: false,
      items: [
        'standards/intro',
        'standards/secs-e5',
        {
          type: 'category',
          label: 'SEMI标准合集',
          collapsible: true,
          collapsed: true,
          items: [
        {
          type: 'category',
          label: 'C系列 - 其他 (Others)',
          collapsible: true,
          collapsed: true,
          items: [
            'standards/semi/semi-chapter-133',
            'standards/semi/semi-chapter-096',
            'standards/semi/semi-chapter-134',
            'standards/semi/semi-chapter-135',
            'standards/semi/semi-chapter-136',
            'standards/semi/semi-chapter-097'
          ],
        },
        {
          type: 'category',
          label: 'D系列 - 文档 (Documentation)',
          collapsible: true,
          collapsed: true,
          items: [
            'standards/semi/semi-chapter-090',
            'standards/semi/semi-chapter-091',
            'standards/semi/semi-chapter-092',
            'standards/semi/semi-chapter-093'
          ],
        },
        {
          type: 'category',
          label: 'E系列 - 设备自动化 (Equipment Automation)',
          collapsible: true,
          collapsed: true,
          items: [
            'standards/semi/semi-chapter-001',
            'standards/semi/semi-chapter-022',
            'standards/semi/semi-chapter-023',
            'standards/semi/semi-chapter-024',
            'standards/semi/semi-chapter-025',
            'standards/semi/semi-chapter-026',
            'standards/semi/semi-chapter-027',
            'standards/semi/semi-chapter-002',
            'standards/semi/semi-chapter-003',
            'standards/semi/semi-chapter-004',
            'standards/semi/semi-chapter-005',
            'standards/semi/semi-chapter-028',
            'standards/semi/semi-chapter-031',
            'standards/semi/semi-chapter-033',
            'standards/semi/semi-chapter-034',
            'standards/semi/semi-chapter-035',
            'standards/semi/semi-chapter-036',
            'standards/semi/semi-chapter-037',
            'standards/semi/semi-chapter-038',
            'standards/semi/semi-chapter-006',
            'standards/semi/semi-chapter-007',
            'standards/semi/semi-chapter-008',
            'standards/semi/semi-chapter-009',
            'standards/semi/semi-chapter-045',
            'standards/semi/semi-chapter-046',
            'standards/semi/semi-chapter-010',
            'standards/semi/semi-chapter-011',
            'standards/semi/semi-chapter-012',
            'standards/semi/semi-chapter-047',
            'standards/semi/semi-chapter-048',
            'standards/semi/semi-chapter-013',
            'standards/semi/semi-chapter-014',
            'standards/semi/semi-chapter-049',
            'standards/semi/semi-chapter-050',
            'standards/semi/semi-chapter-051',
            'standards/semi/semi-chapter-052',
            'standards/semi/semi-chapter-053',
            'standards/semi/semi-chapter-015',
            'standards/semi/semi-chapter-054',
            'standards/semi/semi-chapter-055',
            'standards/semi/semi-chapter-056',
            'standards/semi/semi-chapter-016',
            'standards/semi/semi-chapter-057',
            'standards/semi/semi-chapter-059',
            'standards/semi/semi-chapter-017',
            'standards/semi/semi-chapter-018',
            'standards/semi/semi-chapter-019',
            'standards/semi/semi-chapter-062',
            'standards/semi/semi-chapter-020',
            'standards/semi/semi-chapter-063',
            'standards/semi/semi-chapter-064',
            'standards/semi/semi-chapter-065',
            'standards/semi/semi-chapter-070',
            'standards/semi/semi-chapter-071',
            'standards/semi/semi-chapter-021',
            'standards/semi/semi-chapter-072'
          ],
        },
        {
          type: 'category',
          label: 'F系列 - 设施 (Facilities)',
          collapsible: true,
          collapsed: true,
          items: [
            'standards/semi/semi-chapter-076',
            'standards/semi/semi-chapter-077',
            'standards/semi/semi-chapter-078',
            'standards/semi/semi-chapter-079',
            'standards/semi/semi-chapter-080',
            'standards/semi/semi-chapter-081',
            'standards/semi/semi-chapter-082',
            'standards/semi/semi-chapter-083',
            'standards/semi/semi-chapter-084',
            'standards/semi/semi-chapter-085',
            'standards/semi/semi-chapter-086',
            'standards/semi/semi-chapter-087',
            'standards/semi/semi-chapter-088',
            'standards/semi/semi-chapter-089'
          ],
        },
        {
          type: 'category',
          label: 'G系列 - 气体 (Gases)',
          collapsible: true,
          collapsed: true,
          items: [
            'standards/semi/semi-chapter-122',
            'standards/semi/semi-chapter-123',
            'standards/semi/semi-chapter-124',
            'standards/semi/semi-chapter-125',
            'standards/semi/semi-chapter-126',
            'standards/semi/semi-chapter-127',
            'standards/semi/semi-chapter-128',
            'standards/semi/semi-chapter-129',
            'standards/semi/semi-chapter-130'
          ],
        },
        {
          type: 'category',
          label: 'M系列 - 材料 (Materials)',
          collapsible: true,
          collapsed: true,
          items: [
            'standards/semi/semi-chapter-098',
            'standards/semi/semi-chapter-099',
            'standards/semi/semi-chapter-100',
            'standards/semi/semi-chapter-101',
            'standards/semi/semi-chapter-102',
            'standards/semi/semi-chapter-103',
            'standards/semi/semi-chapter-104',
            'standards/semi/semi-chapter-105',
            'standards/semi/semi-chapter-106',
            'standards/semi/semi-chapter-107',
            'standards/semi/semi-chapter-108',
            'standards/semi/semi-chapter-109',
            'standards/semi/semi-chapter-110'
          ],
        },
        {
          type: 'category',
          label: 'P系列 - 光掩模 (Photomask)',
          collapsible: true,
          collapsed: true,
          items: [
            'standards/semi/semi-chapter-111',
            'standards/semi/semi-chapter-113',
            'standards/semi/semi-chapter-114',
            'standards/semi/semi-chapter-115',
            'standards/semi/semi-chapter-116',
            'standards/semi/semi-chapter-117',
            'standards/semi/semi-chapter-118',
            'standards/semi/semi-chapter-119',
            'standards/semi/semi-chapter-121'
          ],
        },
        {
          type: 'category',
          label: 'S系列 - 安全 (Safety)',
          collapsible: true,
          collapsed: true,
          items: [
            'standards/semi/semi-chapter-137',
            'standards/semi/semi-chapter-138',
            'standards/semi/semi-chapter-139',
            'standards/semi/semi-chapter-140',
            'standards/semi/semi-chapter-141',
            'standards/semi/semi-chapter-142',
            'standards/semi/semi-chapter-143',
            'standards/semi/semi-chapter-144'
          ],
        },
        {
          type: 'category',
          label: 'T系列 - 追溯性 (Traceability)',
          collapsible: true,
          collapsed: true,
          items: [
            'standards/semi/semi-chapter-152',
            'standards/semi/semi-chapter-153',
            'standards/semi/semi-chapter-154',
            'standards/semi/semi-chapter-155',
            'standards/semi/semi-chapter-156',
            'standards/semi/semi-chapter-157',
            'standards/semi/semi-chapter-159'
          ],
        }
          ],
        },
        {
          type: 'category',
          label: '总线协议',
          collapsible: true,
          collapsed: true,
          items: [
            'standards/bus/amba-axi',
            'standards/bus/i2c-spi',
          ],
        },
        {
          type: 'category',
          label: '存储协议',
          collapsible: true,
          collapsed: true,
          items: [
            'standards/memory/ddr4-ddr5',
          ],
        },
      ],
    },
  ],
};
